version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: agri
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: on-failure
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    restart: on-failure
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/usr/src/app

volumes:
  pgdata:
